[package]
name = "blutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
taap = "0.1.4"
clap = "4.5.4"
